language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
branches:
  only:
  - master

before_script:
- git clone https://github.com/Sheridan/cpptoolslib.git
- cd cpptoolslib
- make release
- make install_release
- cd ..
script:
- make debug
after_success:
- make install_debug
- LD_LIBRARY_PATH="/usr/local/lib" .build/debug/lltest
- cat lltest.log

notifications:
  email:
    recipients:
    - gorlov.maxim@gmail.com
    on_success: change
    on_failure: always
